// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njasjoepdafcpjicrfud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qYXNqb2VwZGFmY3BqaWNyZnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NTE0MDYsImV4cCI6MjA1NDIyNzQwNn0.oBIOYkKJGozaYJEnDsfSmDA5YBqmK7Gl_fKFANetma8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);